- name: Create "{{ var_kube_addons_dir }}"
  file:
    path: "{{ var_kube_addons_dir }}"
    state: directory
    mode: 0750
    recurse: yes

- name: Create kube-flannel.yml
  template:
    src: kube-flannel.yml.j2
    dest: "{{ var_kube_addons_dir }}/kube-flannel.yml"

- name: Create kube-flannel
  shell:
    cmd: kubectl apply -f kube-flannel.yml
    chdir: "{{ var_kube_addons_dir }}"
