- name: Create "{{ var_kube_addons_dir }}"
  file:
    path: "{{ var_kube_addons_dir }}"
    state: directory
    mode: 0750
    recurse: yes

- name: Create kube-proxy.yaml
  template:
    src: kube-proxy.yaml.j2
    dest: "{{ var_kube_addons_dir }}/kube-proxy.yaml"

- name: Create kube-proxy
  shell:
    cmd: kubectl create -f kube-proxy.yaml
    #cmd: ls
    chdir: "{{ var_kube_addons_dir }}"
