# https://matthewpalmer.net/kubernetes-app-developer/articles/configmap-example-yaml.html

---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: example-configmap 
data:
  # Configuration values can be set as key-value properties
  cm_database: mongodb
  cm_database_uri: mongodb://localhost:27017
  
  # Or set as complete file contents (even JSON!)
  # note the difference with /, \ and | (do env in the pod and see the difference)
  cm-keys1: / 
    cm_image.public.key1=771 
    cm_rsa.public.key1=42
  cm-keys2: \ 
    cm_image.public.key2=771 
    cm_rsa.public.key2=42
  cm-keys3: |-
    cm_image.public.key3=771 
    cm_rsa.public.key3=42
  cm-keys4:  
    cm_image.public.key4=771 
    cm_rsa.public.key4=42
---
kind: Pod 
apiVersion: v1 
metadata:
  name: alpine-pod-cm-envvar
spec:
  containers:
    - name: env-var-configmap
      image: alpine
      command:
        - /bin/sh
        - "-c"
        - "tail -f /dev/null"
      imagePullPolicy: IfNotPresent
      # This gets all variables
      #envFrom:
        #- configMapRef:
            #name: example-configmap
      # This sets specific variables
      env:
        # Define the environment variable
        - name: cm_image_public_key3_env
          valueFrom:
            configMapKeyRef
              name: example-configmap
              #key: cm-keys3
              key: cm_image.public.key3
