- name: Create kubelet-config.yaml
  template:
    src: kubelet-config.yaml.j2
    dest: "{{ var_kube_etc_dir }}/kubelet-config.yaml"

- name: Create 10-kubeadm.conf
  template:
    src: 10-kubeadm.conf.j2
    dest: "{{ var_usr_systemd_kubelet_dir }}/10-kubeadm.conf"

- name: Start kubelet
  systemd:
    name: kubelet
    daemon_reload: yes
    enabled: yes
    state: restarted

- pause:
    minutes: 5
