- name: Copy etcd.service
  template:
    src: files/etcd.service
    dest: /etc/systemd/system/etcd.service
    mode: "u=rw,g=r"

- name: Start etcd service
  systemd:
    name: etcd
    daemon_reload: yes
    enabled: yes
    state: restarted
