- name: Copy files to machine
  copy:
    src: files/.
    dest: "{{ var_kube_certs_workdir }}"
    mode: "u=rw,g=r,o=r"

#- name: Find all files
  #find:
    #paths: "{{ var_kube_certs_workdir }}"
    #patterns: "*.*"
  #register: files_to_change
#
#- name: Modify the file permissions
  #file:
    #path: "{{ item.path }}"
    #mode: 0640
  #with_items: "{{ files_to_change.files }}"

# From templates
- name: Copy kubelet-csr json file from template
  template:
    src: kubelet-csr.json.j2
    dest: "{{ var_kube_certs_workdir }}/kubelet-csr.json"
    mode: "u=rw,g=r,o=r"

- name: Copy kubelet-gen.sh from template
  template:
    src: kubelet-gen.sh.j2
    dest: "{{ var_kube_certs_workdir }}/kubelet-gen.sh"
    mode: "u=rwx,g=r,o=r"

- name: Copy kubernetes-gen.sh from template
  template:
    src: kubernetes-gen.sh.j2
    dest: "{{ var_kube_certs_workdir }}/kubernetes-gen.sh"
    mode: "u=rwx,g=r,o=r"

- name: Copy kubeconfig-kube-proxy-gen.sh from template
  template:
    src: kubeconfig-kube-proxy-gen.sh.j2
    dest: "{{ var_kube_certs_workdir }}/kubeconfig-kube-proxy-gen.sh"
    mode: "u=rwx,g=r,o=r"

- name: Copy kubeconfig-kubelet-gen.sh from template
  template:
    src: kubeconfig-kubelet-gen.sh.j2
    dest: "{{ var_kube_certs_workdir }}/kubeconfig-kubelet-gen.sh"
    mode: "u=rwx,g=r,o=r"

# Change shell files to executables
- name: Find shell files
  find:
    paths: "{{ var_kube_certs_workdir }}"
    patterns: "*.sh"
  register: files_to_change_to_x

- name: Modify the file permissions
  file:
    path: "{{ item.path }}"
    mode: "u=rwx,g=r,o=r"
  with_items: "{{ files_to_change_to_x.files }}"

