- name: Create certs generation directory
  file:
    path: "{{ var_kube_certs_workdir }}"
    state: directory  
    mode: 0750
    recurse: yes

- name: Create "{{ var_kube_certs_dir }}"
  file:
    path: "{{ var_kube_certs_dir }}"
    state: directory  
    mode: 0750
    recurse: yes

- name: Create "{{ var_kube_manifests_dir }}"
  file:
    path: "{{ var_kube_manifests_dir }}"
    state: directory  
    mode: 0750
    recurse: yes

- name: Create "{{ var_kube_addons_dir }}"
  file:
    path: "{{ var_kube_addons_dir }}"
    state: directory  
    mode: 0750
    recurse: yes

- name: Create ~/.kube
  file:
    path: /root/.kube
    state: directory  
    mode: 0750
    recurse: yes
